# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slicer/slicer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Slicer(object):
    def setupUi(self, Slicer):
        Slicer.setObjectName(_fromUtf8("Slicer"))
        Slicer.resize(800, 257)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Slicer.sizePolicy().hasHeightForWidth())
        Slicer.setSizePolicy(sizePolicy)
        self.formLayout = QtGui.QFormLayout(Slicer)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.imageFileLabel = QtGui.QLabel(Slicer)
        self.imageFileLabel.setObjectName(_fromUtf8("imageFileLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.imageFileLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtImageFile = QtGui.QLineEdit(Slicer)
        self.txtImageFile.setObjectName(_fromUtf8("txtImageFile"))
        self.horizontalLayout_2.addWidget(self.txtImageFile)
        self.btnOpenImageFile = QtGui.QPushButton(Slicer)
        self.btnOpenImageFile.setObjectName(_fromUtf8("btnOpenImageFile"))
        self.horizontalLayout_2.addWidget(self.btnOpenImageFile)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.lblPieceCount = QtGui.QLabel(Slicer)
        self.lblPieceCount.setObjectName(_fromUtf8("lblPieceCount"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblPieceCount)
        self.pieceCount = QtGui.QWidget(Slicer)
        self.pieceCount.setObjectName(_fromUtf8("pieceCount"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pieceCount)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pc_20 = QtGui.QRadioButton(self.pieceCount)
        self.pc_20.setChecked(True)
        self.pc_20.setObjectName(_fromUtf8("pc_20"))
        self.horizontalLayout.addWidget(self.pc_20)
        self.pc_50 = QtGui.QRadioButton(self.pieceCount)
        self.pc_50.setObjectName(_fromUtf8("pc_50"))
        self.horizontalLayout.addWidget(self.pc_50)
        self.pc_100 = QtGui.QRadioButton(self.pieceCount)
        self.pc_100.setObjectName(_fromUtf8("pc_100"))
        self.horizontalLayout.addWidget(self.pc_100)
        self.pc_200 = QtGui.QRadioButton(self.pieceCount)
        self.pc_200.setObjectName(_fromUtf8("pc_200"))
        self.horizontalLayout.addWidget(self.pc_200)
        self.pc_500 = QtGui.QRadioButton(self.pieceCount)
        self.pc_500.setObjectName(_fromUtf8("pc_500"))
        self.horizontalLayout.addWidget(self.pc_500)
        self.pc_custom = QtGui.QRadioButton(self.pieceCount)
        self.pc_custom.setObjectName(_fromUtf8("pc_custom"))
        self.horizontalLayout.addWidget(self.pc_custom)
        self.pc_box = QtGui.QSpinBox(self.pieceCount)
        self.pc_box.setMaximum(2000)
        self.pc_box.setSingleStep(10)
        self.pc_box.setProperty("value", 50)
        self.pc_box.setObjectName(_fromUtf8("pc_box"))
        self.horizontalLayout.addWidget(self.pc_box)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.pieceCount)
        self.gridTypeLabel = QtGui.QLabel(Slicer)
        self.gridTypeLabel.setObjectName(_fromUtf8("gridTypeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.gridTypeLabel)
        self.cboGridType = QtGui.QComboBox(Slicer)
        self.cboGridType.setObjectName(_fromUtf8("cboGridType"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cboGridType)
        self.saveToLabel = QtGui.QLabel(Slicer)
        self.saveToLabel.setObjectName(_fromUtf8("saveToLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.saveToLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.txtSaveTo = QtGui.QLineEdit(Slicer)
        self.txtSaveTo.setObjectName(_fromUtf8("txtSaveTo"))
        self.horizontalLayout_3.addWidget(self.txtSaveTo)
        self.btnSaveTo = QtGui.QPushButton(Slicer)
        self.btnSaveTo.setObjectName(_fromUtf8("btnSaveTo"))
        self.horizontalLayout_3.addWidget(self.btnSaveTo)
        self.formLayout.setLayout(11, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.buttonBox = QtGui.QDialogButtonBox(Slicer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.buttonBox)
        self.previewLabel = QtGui.QLabel(Slicer)
        self.previewLabel.setObjectName(_fromUtf8("previewLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.previewLabel)
        self.previewImage = QtGui.QLabel(Slicer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewImage.sizePolicy().hasHeightForWidth())
        self.previewImage.setSizePolicy(sizePolicy)
        self.previewImage.setMinimumSize(QtCore.QSize(600, 300))
        self.previewImage.setBaseSize(QtCore.QSize(400, 300))
        self.previewImage.setFrameShape(QtGui.QFrame.Panel)
        self.previewImage.setFrameShadow(QtGui.QFrame.Sunken)
        self.previewImage.setObjectName(_fromUtf8("previewImage"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.previewImage)
        self.flipSlider = QtGui.QSlider(Slicer)
        self.flipSlider.setMaximum(100)
        self.flipSlider.setProperty("value", 10)
        self.flipSlider.setOrientation(QtCore.Qt.Horizontal)
        self.flipSlider.setObjectName(_fromUtf8("flipSlider"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.flipSlider)
        self.label = QtGui.QLabel(Slicer)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(Slicer)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.curvinessSlider = QtGui.QSlider(Slicer)
        self.curvinessSlider.setMinimum(-100)
        self.curvinessSlider.setMaximum(100)
        self.curvinessSlider.setProperty("value", -50)
        self.curvinessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curvinessSlider.setObjectName(_fromUtf8("curvinessSlider"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.curvinessSlider)
        self.label_3 = QtGui.QLabel(Slicer)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.plugSizeSlider = QtGui.QSlider(Slicer)
        self.plugSizeSlider.setMinimum(-50)
        self.plugSizeSlider.setMaximum(50)
        self.plugSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plugSizeSlider.setObjectName(_fromUtf8("plugSizeSlider"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.plugSizeSlider)
        self.label_5 = QtGui.QLabel(Slicer)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_5)
        self.plugPosVarSlider = QtGui.QSlider(Slicer)
        self.plugPosVarSlider.setMinimum(1)
        self.plugPosVarSlider.setMaximum(100)
        self.plugPosVarSlider.setProperty("value", 12)
        self.plugPosVarSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plugPosVarSlider.setObjectName(_fromUtf8("plugPosVarSlider"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.plugPosVarSlider)
        self.label_6 = QtGui.QLabel(Slicer)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_6)
        self.plugShapeVarSlider = QtGui.QSlider(Slicer)
        self.plugShapeVarSlider.setMinimum(1)
        self.plugShapeVarSlider.setMaximum(100)
        self.plugShapeVarSlider.setProperty("value", 25)
        self.plugShapeVarSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plugShapeVarSlider.setObjectName(_fromUtf8("plugShapeVarSlider"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.plugShapeVarSlider)
        self.label_4 = QtGui.QLabel(Slicer)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_4)
        self.curvinessVarSlider = QtGui.QSlider(Slicer)
        self.curvinessVarSlider.setMinimum(1)
        self.curvinessVarSlider.setMaximum(100)
        self.curvinessVarSlider.setOrientation(QtCore.Qt.Horizontal)
        self.curvinessVarSlider.setObjectName(_fromUtf8("curvinessVarSlider"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.curvinessVarSlider)
        self.imageFileLabel.setBuddy(self.txtImageFile)
        self.lblPieceCount.setBuddy(self.pc_20)
        self.gridTypeLabel.setBuddy(self.cboGridType)
        self.saveToLabel.setBuddy(self.txtSaveTo)

        self.retranslateUi(Slicer)
        self.cboGridType.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Slicer.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Slicer.reject)
        QtCore.QMetaObject.connectSlotsByName(Slicer)

    def retranslateUi(self, Slicer):
        Slicer.setWindowTitle(_translate("Slicer", "New Puzzle", None))
        self.imageFileLabel.setText(_translate("Slicer", "I&mage File", None))
        self.btnOpenImageFile.setText(_translate("Slicer", "Open...", None))
        self.lblPieceCount.setText(_translate("Slicer", "&Piece Count:", None))
        self.pc_20.setText(_translate("Slicer", "&20", None))
        self.pc_50.setText(_translate("Slicer", "&50", None))
        self.pc_100.setText(_translate("Slicer", "&100", None))
        self.pc_200.setText(_translate("Slicer", "2&00", None))
        self.pc_500.setText(_translate("Slicer", "500", None))
        self.pc_custom.setText(_translate("Slicer", "&ca.:", None))
        self.gridTypeLabel.setText(_translate("Slicer", "&Grid type:", None))
        self.saveToLabel.setText(_translate("Slicer", "Save &to:", None))
        self.btnSaveTo.setText(_translate("Slicer", "Open...", None))
        self.previewLabel.setText(_translate("Slicer", "Grid preview:", None))
        self.previewImage.setText(_translate("Slicer", "TextLabel", None))
        self.label.setText(_translate("Slicer", "Knob flip:", None))
        self.label_2.setText(_translate("Slicer", "Edge curviness:", None))
        self.label_3.setText(_translate("Slicer", "Plug size:", None))
        self.label_5.setText(_translate("Slicer", "Plug pos. variation", None))
        self.label_6.setText(_translate("Slicer", "Plug shape variation", None))
        self.label_4.setText(_translate("Slicer", "Curviness variation:", None))

