# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtpuzzle/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/applications-graphics.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mainView = MainView(self.centralwidget)
        self.mainView.setFrameShape(QtGui.QFrame.NoFrame)
        self.mainView.setFrameShadow(QtGui.QFrame.Plain)
        self.mainView.setLineWidth(0)
        self.mainView.setObjectName(_fromUtf8("mainView"))
        self.verticalLayout_2.addWidget(self.mainView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInsert = QtGui.QMenu(self.menubar)
        self.menuInsert.setObjectName(_fromUtf8("menuInsert"))
        self.menuNetwork = QtGui.QMenu(self.menubar)
        self.menuNetwork.setObjectName(_fromUtf8("menuNetwork"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.action_Quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_Quit.setIcon(icon)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_view_all = QtGui.QAction(MainWindow)
        self.action_view_all.setObjectName(_fromUtf8("action_view_all"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionAutosave = QtGui.QAction(MainWindow)
        self.actionAutosave.setCheckable(True)
        self.actionAutosave.setChecked(True)
        self.actionAutosave.setObjectName(_fromUtf8("actionAutosave"))
        self.actionSelRearrange = QtGui.QAction(MainWindow)
        self.actionSelRearrange.setObjectName(_fromUtf8("actionSelRearrange"))
        self.actionReset = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-revert"))
        self.actionReset.setIcon(icon)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionSelClear = QtGui.QAction(MainWindow)
        self.actionSelClear.setObjectName(_fromUtf8("actionSelClear"))
        self.actionNewPuzzle = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.actionNewPuzzle.setIcon(icon)
        self.actionNewPuzzle.setObjectName(_fromUtf8("actionNewPuzzle"))
        self.actionLocalhost = QtGui.QAction(MainWindow)
        self.actionLocalhost.setObjectName(_fromUtf8("actionLocalhost"))
        self.actionNickname = QtGui.QAction(MainWindow)
        self.actionNickname.setObjectName(_fromUtf8("actionNickname"))
        self.actionShortcutHelp = QtGui.QAction(MainWindow)
        self.actionShortcutHelp.setObjectName(_fromUtf8("actionShortcutHelp"))
        self.actionFullscreen = QtGui.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName(_fromUtf8("actionFullscreen"))
        self.menuFile.addAction(self.actionNewPuzzle)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionAutosave)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuInsert.addAction(self.actionSelRearrange)
        self.menuInsert.addAction(self.actionSelClear)
        self.menuNetwork.addAction(self.actionNickname)
        self.menuNetwork.addSeparator()
        self.menu.addAction(self.actionShortcutHelp)
        self.menu_View.addAction(self.actionFullscreen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuNetwork.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.action_view_all, QtCore.SIGNAL(_fromUtf8("activated()")), self.mainView.viewAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Puzzle", None))
        self.menuFile.setTitle(_translate("MainWindow", "&Puzzle", None))
        self.menuInsert.setTitle(_translate("MainWindow", "Se&lection", None))
        self.menuNetwork.setTitle(_translate("MainWindow", "&Network", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_view_all.setText(_translate("MainWindow", "View all", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open...", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save &as...", None))
        self.actionAutosave.setText(_translate("MainWindow", "A&utosave", None))
        self.actionSelRearrange.setText(_translate("MainWindow", "&Rearrange", None))
        self.actionSelRearrange.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionReset.setText(_translate("MainWindow", "&Restart", None))
        self.actionSelClear.setText(_translate("MainWindow", "&Clear", None))
        self.actionSelClear.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionNewPuzzle.setText(_translate("MainWindow", "&New Puzzle", None))
        self.actionNewPuzzle.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionLocalhost.setText(_translate("MainWindow", "localhost", None))
        self.actionNickname.setText(_translate("MainWindow", "&Nickname", None))
        self.actionShortcutHelp.setText(_translate("MainWindow", "&Shortcut Help", None))
        self.actionShortcutHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionFullscreen.setText(_translate("MainWindow", "&Fullscreen", None))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "Ctrl+F", None))

from .main_view import MainView
from . import icons_rc
